---
- name: Update apt cache (Debian-based)
  ansible.builtin.apt:
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"

- name: Update yum cache (Red Hat-based)
  ansible.builtin.dnf:
    update_cache: true
  when: ansible_facts['os_family'] == "RedHat"

- name: Install required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - wget
    - vim
    - qemu-guest-agent
