---
- name: Authenticate with Proxmox API
  hosts: localhost
  gather_facts: false
  roles:
    - proxmox_api_authentication

- name: Start all Proxmox VMs
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include role for each VM in the inventory
      ansible.builtin.include_role:
        name: common
        tasks_from: start_vm
      loop: "{{ groups['all'] }}"  # Loop over all VMs in the inventory
      loop_control:
        loop_var: vm_name
