status_retries: 10
status_delay: 10
ssh_wait_timeout: 300
vault_role_id: "{{ lookup('env', 'VAULT_ROLE_ID') }}"
vault_secret_id: "{{ lookup('env', 'VAULT_SECRET_ID') }}"
vault_url: "{{ lookup('env', 'VAULT_SECRET_ID') }}"
vault_secret_path: "secret/data/proxmox"