---
- name: Check if kubeadm is already initialized
  ansible.builtin.include_role:
    name: common
    tasks_from: is_kubeadm_initialized
  tags: initialization

- name: Initialize kubeadm
  ansible.builtin.include_tasks: tasks/init.yml
  when: not kubeadm_initialized
  tags: initialization

- name: Generate join commands
  ansible.builtin.include_tasks: tasks/join_commands_generation.yml
  when: kubeadm_initialized
  tags: join_commands

- name: Fetch admin.conf to localhost
  ansible.builtin.include_tasks: tasks/fetch_admin_conf.yml
  when: kubeadm_initialized
  tags: fetch_config
