nodes:
  control_plane:
    count: 3
    first_id: "100"
    names_prefix: control-plane-
    ip_range_start: 10
    disk_size: "50G"
    cores: 4
    memory: 8192
    user: sudo-amine
  workers:
    count: 5
    first_id: "200"
    names_prefix: worker-node-
    ip_range_start: 20
    disk_size: "50G"
    cores: 2
    memory: 4096
    user: sudo-amine
network:
  bridge: vmbr0
  gateway: 192.168.1.1
  subnet: "24"
  gateway_subnet: 192.168.1.0/24
proxmox:
  host: proxmox.local
  node: proxmox
  api_user: terraform@pve
  token_id: tid
  storage_local: local
  storage_main: local-lvm-2
ssh:
  public_key_path: ~/.ssh/id_rsa.pub
  private_key_path: ~/.ssh/id_rsa
vault:
  secret_path: secret/data/proxmox
vm_template:
  id: "9001"
  name: vm-template
  disk_size: "8G"
  ip: 192.168.1.101
  user: sudo-amine
  image_name: "jammy-server-cloudimg-amd64.img"
  image_url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"