vm_template:
  id: "9001"
  name: vm-template
  disk_size: "8G"
  ip: 192.168.1.101
  user: sudo-amine
  image_name: "jammy-server-cloudimg-amd64.img"
  image_url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
