---
- name: Start all Proxmox VMs
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include role for each VM in the inventory
      ansible.builtin.include_role:
        name: start_vm
      loop: "{{ groups['control_plane'] | union(groups['worker_nodes']) }}"
      loop_control:
        loop_var: vm_name
        extended: true
      vars:
        vm_vars: "{{ hostvars[vm_name] }}"
