---
- name: Start VM and Configure SSH
  hosts: localhost
  gather_facts: false
  roles:
    - start_vm

- name: Install and Configure VM
  hosts: vm-template
  gather_facts: true
  become: true
  roles:
    - update_package
    - install_dependencies
    - configure_qemu
    - add_control_plane_endpoint

- name: Stop VM
  hosts: localhost
  gather_facts: false
  roles:
    - stop_vm
